# -*- coding: utf-8 -*-
"""30thJuly_USHoney_Dev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B75Dl_Q1B_Z_RwQoCLBWgHNSkWMuvT51

#**Hello Everyone 👋**#
  # **Hope you all are doing great. This is Dev on this end, and I welcome you all in this session. Let's wait for few minutes, so that your peers can also join. We will be kicking off the session at 7:07 AM**

#**Background / Scenario**#


**US Honey Case Study**

**PREFACE**

  **In 2006, global concern was raised over the rapid decline in the honeybee population, an integral component of American honey agriculture. Large numbers of hives were lost to `Colony Collapse Disorder`, a phenomenon of disappearing worker bees causing the remaining hive colony to collapse. Speculation to the cause of this disorder points to hive diseases and pesticides harming the pollinators, though no overall consensus has been reached. The U.S. used to locally produce over half the honey it consumes per year. Now, honey mostly comes from overseas, with 350 of the 400 million pounds of honey consumed every year originating from imports. This dataset provides insight into honey production supply and demand in America from 1998 to 2021.**

#**OBJECTIVE**#

****Visualize how the honey production is changed over the year (1998 - 2021) in US****

#**QUESTION**#

**How has honey production yield changed from 1998 to 2016?**

**Over time, what are the major production trends been across the states?**

**Are there any patterns that can be observed between total honey production and value of production every year?**

**How has value of production, which in some sense could be tied to demand, changed every year?**

<hr>

# **Step 1 - Requirement Phase**
  * **What do we need in the project>**
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""<hr>

# **Step 2 - Data Loading and Inspection Phase**

**Data Loading**
"""

df = pd.read_csv("/content/US_honey_dataset.csv")

"""**Data Inspection**"""

# First view perspective ->
df.head()

"""**Insights / Inference / Reference Points**
  * **The column Unname: 0, it's not important to us**
"""

df.tail()

"""<hr>

**Shape Inspection**
"""

a = df.shape
print(f"Rows: {a[0]} and Columns: {a[1]}")

"""<hr>

**Brief on the data**
"""

df.info()

"""* **The unnamed column can dropped, as there is no need to the columns**
* **Most of my data is numerical nature**
* **The year columns needs to be worked on for conversion of dtype into object or date**
"""

# Dropping the unnname column
df = df.drop("Unnamed: 0", axis = 1)

"""<hr>

# **Step 3 - Data Preprocessing**

**Null Values**
"""

df.isnull().sum()

"""**Duplicates**"""

df.duplicated()

"""<hr>

# **Step 4 - Exploratory Data Analysis (EDA) / Deep Analysis**

<hr>

* **How many states were involved in this business?**
"""

df["state"].unique() # return array of the elements

df["state"].nunique() #->

"""<hr>

**What is the tenure of the data that we are look on?**
"""

df["year"].unique()

df["year"].max() - df["year"].min()

"""**Which were the states that were having the highest production**"""

df.groupby("state")["production"].sum().sort_values(ascending = False)

"""**The climate in the top production state would have been very adequate for honey production, that is the reason why the production are very high (Assumption)**

Graphical Analysis
"""

plt.figure(figsize = (10, 8))
df.groupby("state")["production"].sum().sort_values(ascending = False).plot(kind = "bar")
plt.xlabel("States")
plt.show()

"""**NorthDakota is the one leading, and MaryLand is the one having least production**

<hr>

**Analysing the trend in the data**
"""

trend_data = df.drop("state", axis = 1).groupby("year").mean()

trend_data.head()

"""Trend on Colony"""

