# -*- coding: utf-8 -*-
"""Numpy 17 July.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S47B3xMQct_GgPiAqN_BYUSMeF4uPo-J
"""

import numpy as np

"""### Manual Creation of the arrays"""

list1 = [10, 20, 30, 40, 50, 60]

list1 * 3

twice = []

for value in list1:
  twice.append(value * 2)

twice

arr1 = np.array(list1)

print(arr1)

arr1 * 2

set(arr1)

list2 = [10, 20, 30, 40.2, 55, 87, 99, 'Python']

np.array(list2)

"""### Creation of the arrays using functions

- np.arange
- np.ones
- np.zeros
- np.eye
- np.diag
- np.random.random
- np.random.randint
- np.linspace

#### np.arange
"""

np.arange(100000)

np.arange(500, 5001)  #(start, stop+1)

np.arange(500, 5001, 10)  #(start, stop+1, step)

np.arange(10.0, 51.0, 0.1)

np.arange(10, 51, 1.5)

"""#### np.ones"""

np.ones(10)

np.ones((5,4))

np.ones((5,4), dtype = 'int')

np.ones((5,4)) * 10.5

"""#### np.zeros"""

np.zeros(10)

np.zeros((5,4))

np.zeros((5,4), dtype = 'int')

"""#### **np.eye**"""

np.eye(5)  #identity matrix

np.eye(3) * 5

"""#### **np.diag**"""

np.diag([12, 6, 5, 78, 43])

"""#### **np.random.randint**"""

np.random.randint(10)

np.random.randint(10, 51)

np.random.randint(1, 7)

np.random.randint(1000, 10000)

np.random.randint(1000, 10000, size = 10)

np.random.randint(100, 501, size = (5,4))

"""#### np.random.random"""

np.random.random(5)  #random number between 0.0 and 1.0

np.random.random(5) * 10

np.round((np.random.random(5) * 10), 2)



"""### **Array Mathematics**

1. Basic Mathematical Operations (Today)
2. Advanced Mathematical Operations
"""

arr1 = np.random.randint(10, 51, size = (3,3))
arr2 = np.random.randint(10, 51, size = (3,3))

arr1

arr2

arr1 + arr2

arr1 + 10

arr1 - arr2

arr2 - arr1

arr1 * arr2

arr1 / arr2

arr1 / 2

"""### **Mean, Sum, Min, Max of the given array**"""

